/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BlogCardProps } from "./types/Card";
export { BlogCardProps } from "./types/Card";
export namespace Components {
    interface BlogCard {
        "cardCategory": BlogCardProps['cardCategory'];
        "cardFooterText": BlogCardProps['cardFooterText'];
        "cardImage": BlogCardProps['cardImage'];
        "cardLink": BlogCardProps['cardLink'];
        "cardSummary": BlogCardProps['cardSummary'];
        "cardTitle": BlogCardProps['cardTitle'];
    }
    interface BlogCardWide {
        "cardFooterText": BlogCardProps['cardFooterText'];
        "cardImage": BlogCardProps['cardImage'];
        "cardLink": BlogCardProps['cardLink'];
        "cardSummary": BlogCardProps['cardSummary'];
        "cardTitle": BlogCardProps['cardTitle'];
    }
    interface BlogCards {
    }
    interface BlogCardsWide {
    }
    interface CtaSlider {
        "heading": string;
        "text": string;
    }
}
declare global {
    interface HTMLBlogCardElement extends Components.BlogCard, HTMLStencilElement {
    }
    var HTMLBlogCardElement: {
        prototype: HTMLBlogCardElement;
        new (): HTMLBlogCardElement;
    };
    interface HTMLBlogCardWideElement extends Components.BlogCardWide, HTMLStencilElement {
    }
    var HTMLBlogCardWideElement: {
        prototype: HTMLBlogCardWideElement;
        new (): HTMLBlogCardWideElement;
    };
    interface HTMLBlogCardsElement extends Components.BlogCards, HTMLStencilElement {
    }
    var HTMLBlogCardsElement: {
        prototype: HTMLBlogCardsElement;
        new (): HTMLBlogCardsElement;
    };
    interface HTMLBlogCardsWideElement extends Components.BlogCardsWide, HTMLStencilElement {
    }
    var HTMLBlogCardsWideElement: {
        prototype: HTMLBlogCardsWideElement;
        new (): HTMLBlogCardsWideElement;
    };
    interface HTMLCtaSliderElement extends Components.CtaSlider, HTMLStencilElement {
    }
    var HTMLCtaSliderElement: {
        prototype: HTMLCtaSliderElement;
        new (): HTMLCtaSliderElement;
    };
    interface HTMLElementTagNameMap {
        "blog-card": HTMLBlogCardElement;
        "blog-card-wide": HTMLBlogCardWideElement;
        "blog-cards": HTMLBlogCardsElement;
        "blog-cards-wide": HTMLBlogCardsWideElement;
        "cta-slider": HTMLCtaSliderElement;
    }
}
declare namespace LocalJSX {
    interface BlogCard {
        "cardCategory"?: BlogCardProps['cardCategory'];
        "cardFooterText"?: BlogCardProps['cardFooterText'];
        "cardImage"?: BlogCardProps['cardImage'];
        "cardLink"?: BlogCardProps['cardLink'];
        "cardSummary"?: BlogCardProps['cardSummary'];
        "cardTitle"?: BlogCardProps['cardTitle'];
    }
    interface BlogCardWide {
        "cardFooterText"?: BlogCardProps['cardFooterText'];
        "cardImage"?: BlogCardProps['cardImage'];
        "cardLink"?: BlogCardProps['cardLink'];
        "cardSummary"?: BlogCardProps['cardSummary'];
        "cardTitle"?: BlogCardProps['cardTitle'];
    }
    interface BlogCards {
    }
    interface BlogCardsWide {
    }
    interface CtaSlider {
        "heading"?: string;
        "text"?: string;
    }
    interface IntrinsicElements {
        "blog-card": BlogCard;
        "blog-card-wide": BlogCardWide;
        "blog-cards": BlogCards;
        "blog-cards-wide": BlogCardsWide;
        "cta-slider": CtaSlider;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "blog-card": LocalJSX.BlogCard & JSXBase.HTMLAttributes<HTMLBlogCardElement>;
            "blog-card-wide": LocalJSX.BlogCardWide & JSXBase.HTMLAttributes<HTMLBlogCardWideElement>;
            "blog-cards": LocalJSX.BlogCards & JSXBase.HTMLAttributes<HTMLBlogCardsElement>;
            "blog-cards-wide": LocalJSX.BlogCardsWide & JSXBase.HTMLAttributes<HTMLBlogCardsWideElement>;
            "cta-slider": LocalJSX.CtaSlider & JSXBase.HTMLAttributes<HTMLCtaSliderElement>;
        }
    }
}
