/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BlogCardProps } from "./components/blog-card/blog-card";
export { BlogCardProps } from "./components/blog-card/blog-card";
export namespace Components {
    interface BlogCard {
        "cardCategory": BlogCardProps['cardCategory'];
        "cardImage": BlogCardProps['cardImage'];
        "cardLink": BlogCardProps['cardLink'];
        "cardSummary": BlogCardProps['cardSummary'];
        "cardTitle": BlogCardProps['cardTitle'];
    }
    interface BlogCards {
    }
}
declare global {
    interface HTMLBlogCardElement extends Components.BlogCard, HTMLStencilElement {
    }
    var HTMLBlogCardElement: {
        prototype: HTMLBlogCardElement;
        new (): HTMLBlogCardElement;
    };
    interface HTMLBlogCardsElement extends Components.BlogCards, HTMLStencilElement {
    }
    var HTMLBlogCardsElement: {
        prototype: HTMLBlogCardsElement;
        new (): HTMLBlogCardsElement;
    };
    interface HTMLElementTagNameMap {
        "blog-card": HTMLBlogCardElement;
        "blog-cards": HTMLBlogCardsElement;
    }
}
declare namespace LocalJSX {
    interface BlogCard {
        "cardCategory"?: BlogCardProps['cardCategory'];
        "cardImage"?: BlogCardProps['cardImage'];
        "cardLink"?: BlogCardProps['cardLink'];
        "cardSummary"?: BlogCardProps['cardSummary'];
        "cardTitle"?: BlogCardProps['cardTitle'];
    }
    interface BlogCards {
    }
    interface IntrinsicElements {
        "blog-card": BlogCard;
        "blog-cards": BlogCards;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "blog-card": LocalJSX.BlogCard & JSXBase.HTMLAttributes<HTMLBlogCardElement>;
            "blog-cards": LocalJSX.BlogCards & JSXBase.HTMLAttributes<HTMLBlogCardsElement>;
        }
    }
}
