/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BbButton {
        "variant": 'primary' | 'secondary' | 'tertiary';
    }
    interface BbButtonGroup {
    }
    interface BbDropdown {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLBbButtonElement extends Components.BbButton, HTMLStencilElement {
    }
    var HTMLBbButtonElement: {
        prototype: HTMLBbButtonElement;
        new (): HTMLBbButtonElement;
    };
    interface HTMLBbButtonGroupElement extends Components.BbButtonGroup, HTMLStencilElement {
    }
    var HTMLBbButtonGroupElement: {
        prototype: HTMLBbButtonGroupElement;
        new (): HTMLBbButtonGroupElement;
    };
    interface HTMLBbDropdownElement extends Components.BbDropdown, HTMLStencilElement {
    }
    var HTMLBbDropdownElement: {
        prototype: HTMLBbDropdownElement;
        new (): HTMLBbDropdownElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "bb-button": HTMLBbButtonElement;
        "bb-button-group": HTMLBbButtonGroupElement;
        "bb-dropdown": HTMLBbDropdownElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface BbButton {
        "variant"?: 'primary' | 'secondary' | 'tertiary';
    }
    interface BbButtonGroup {
    }
    interface BbDropdown {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "bb-button": BbButton;
        "bb-button-group": BbButtonGroup;
        "bb-dropdown": BbDropdown;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bb-button": LocalJSX.BbButton & JSXBase.HTMLAttributes<HTMLBbButtonElement>;
            "bb-button-group": LocalJSX.BbButtonGroup & JSXBase.HTMLAttributes<HTMLBbButtonGroupElement>;
            "bb-dropdown": LocalJSX.BbDropdown & JSXBase.HTMLAttributes<HTMLBbDropdownElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
